use crate::i18n::{L10n, Lang};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

macro_rules! map {
    ($($k:expr => $v:expr),* $(,)?) => {{
        let mut m = HashMap::new();
        $(m.insert($k, $v);)*
        m
    }};
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkinPreset {
    pub key: String,
    pub display_name: String,
    pub display_name_key: &'static str,
    pub author: String,
    pub values: HashMap<String, serde_yaml::Value>,
}

pub fn builtin_skins(lang: Lang) -> Vec<SkinPreset> {
    let t = L10n::new(lang);
    vec![
        SkinPreset {
            key: "jianchun".into(),
            display_name: t.t("skin.jianchun").into(),
            display_name_key: "skin.jianchun",
            author: "amzxyz".into(),
            values: map![
                "name".into() => "简纯".into(),
                "author".into() => "amzxyz".into(),
                "back_color".into() => "0xf2f2f2".into(),
                "border_color".into() => "0xCE7539".into(),
                "text_color".into() => "0x3c647e".into(),
                "hilited_text_color".into() => "0x3c647e".into(),
                "hilited_back_color".into() => "0x797954".into(),
                "hilited_comment_text_color".into() => "0xffffff".into(),
                "hilited_candidate_text_color".into() => "0xffffff".into(),
                "hilited_candidate_back_color".into() => "0xCE7539".into(),
                "hilited_label_color".into() => "0xdedede".into(),
                "candidate_text_color".into() => "0x000000".into(),
                "comment_text_color".into() => "0x000000".into(),
                "label_color".into() => "0x91897e".into(),
            ],
        },
        SkinPreset {
            key: "win11_light".into(),
            display_name: t.t("skin.win11_light").into(),
            display_name_key: "skin.win11_light",
            author: "community".into(),
            values: map![
                "name".into() => "Win11浅色 / Win11light".into(),
                "text_color".into() => "0x191919".into(),
                "label_color".into() => "0x191919".into(),
                "hilited_label_color".into() => "0x191919".into(),
                "back_color".into() => "0xf9f9f9".into(),
                "border_color".into() => "0x009e5a00".into(),
                "hilited_mark_color".into() => "0xc06700".into(),
                "hilited_candidate_back_color".into() => "0xf0f0f0".into(),
                "shadow_color".into() => "0x20000000".into(),
            ],
        },
        SkinPreset {
            key: "win11_dark".into(),
            display_name: t.t("skin.win11_dark").into(),
            display_name_key: "skin.win11_dark",
            author: "community".into(),
            values: map![
                "name".into() => "Win11暗色 / Win11Dark".into(),
                "text_color".into() => "0xf9f9f9".into(),
                "label_color".into() => "0xf9f9f9".into(),
                "back_color".into() => "0x2C2C2C".into(),
                "hilited_label_color".into() => "0xf9f9f9".into(),
                "border_color".into() => "0x002C2C2C".into(),
                "hilited_mark_color".into() => "0xFFC24C".into(),
                "hilited_candidate_back_color".into() => "0x383838".into(),
                "shadow_color".into() => "0x20000000".into(),
            ],
        },
        SkinPreset {
            key: "mac_light".into(),
            display_name: t.t("skin.mac_light").into(),
            display_name_key: "skin.mac_light",
            author: "community".into(),
            values: map![
                "name".into() => "Mac 白".into(),
                "text_color".into() => "0x000000".into(),
                "back_color".into() => "0xffffff".into(),
                "border_color".into() => "0xe9e9e9".into(),
                "label_color".into() => "0x999999".into(),
                "hilited_text_color".into() => "0x000000".into(),
                "hilited_back_color".into() => "0xffffff".into(),
                "candidate_text_color".into() => "0x000000".into(),
                "comment_text_color".into() => "0x999999".into(),
                "hilited_candidate_text_color".into() => "0xffffff".into(),
                "hilited_comment_text_color".into() => "0xdddddd".into(),
                "hilited_candidate_back_color".into() => 16740656.into(),
                "hilited_label_color".into() => "0xffffff".into(),
            ],
        },
        SkinPreset {
            key: "wechat".into(),
            display_name: t.t("skin.wechat").into(),
            display_name_key: "skin.wechat",
            author: "community".into(),
            values: map![
                "name".into() => "微信／Wechat".into(),
                "text_color".into() => "0x424242".into(),
                "label_color".into() => "0x999999".into(),
                "back_color".into() => "0xFFFFFF".into(),
                "border_color".into() => "0xFFFFFF".into(),
                "comment_text_color".into() => "0x999999".into(),
                "candidate_text_color".into() => "0x3c3c3c".into(),
                "hilited_comment_text_color".into() => "0xFFFFFF".into(),
                "hilited_back_color".into() => "0x79af22".into(),
                "hilited_text_color".into() => "0xFFFFFF".into(),
                "hilited_label_color".into() => "0xFFFFFF".into(),
                "hilited_candidate_back_color".into() => "0x79af22".into(),
                "shadow_color".into() => "0x20000000".into(),
            ],
        },
        SkinPreset {
            key: "Lumk_light".into(),
            display_name: t.t("skin.lumk_light").into(),
            display_name_key: "skin.lumk_light",
            author: "Lumk X".into(),
            values: map![
                "name".into() => "鹿鸣／Lumk light".into(),
                "author".into() => "Lumk X <x@xx.cc>".into(),
                "back_color".into() => "0xF9F9F9".into(),
                "border_color".into() => "0xE2E7F5".into(),
                "candidate_text_color".into() => "0x121212".into(),
                "comment_text_color".into() => "0x8E8E8E".into(),
                "hilited_candidate_back_color".into() => "0xECE4FC".into(),
                "hilited_candidate_label_color".into() => "0xB18FF4".into(),
                "hilited_candidate_text_color".into() => "0x7A40EC".into(),
                "hilited_label_color".into() => "0xA483EC".into(),
                "hilited_mark_color".into() => "0x7A40EC".into(),
                "label_color".into() => "0x888785".into(),
                "text_color".into() => "0x8100EB".into(),
                "shadow_color".into() => "0x20000000".into(),
            ],
        },
        SkinPreset {
            key: "amber-7".into(),
            display_name: t.t("skin.amber_7").into(),
            display_name_key: "skin.amber_7",
            author: "五笔小筑".into(),
            values: map![
                "name".into() => "淡白/weasel".into(),
                "author".into() => "五笔小筑 <wubixiaozhu@126.com>".into(),
                "back_color".into() => "0xffffff".into(),
                "border_color".into() => "0xE99321".into(),
                "shadow_color".into() => "0x00000000".into(),
                "text_color".into() => "0xE99321".into(),
                "hilited_text_color".into() => "0x2238dc".into(),
                "hilited_back_color".into() => "0xffffff".into(),
                "hilited_shadow_color".into() => "0x00000000".into(),
                "nextpage_color".into() => "0x0000FF".into(),
                "prevpage_color".into() => "0x0000FF".into(),
                "hilited_mark_color".into() => "0x00000000".into(),
                "hilited_label_color".into() => "0x2021FF".into(),
                "hilited_candidate_text_color".into() => "0x2021FF".into(),
                "hilited_comment_text_color".into() => "0x000000".into(),
                "hilited_candidate_back_color".into() => "0xECF1FC".into(),
                "hilited_candidate_border_color".into() => "0xCFDCFD".into(),
                "hilited_candidate_shadow_color".into() => "0x00000000".into(),
                "label_color".into() => "0xE99321".into(),
                "candidate_text_color".into() => "0xE99321".into(),
                "comment_text_color".into() => "0x000000".into(),
                "candidate_back_color".into() => "0xffffff".into(),
                "candidate_border_color".into() => "0xffffff".into(),
                "candidate_shadow_color".into() => "0x00000000".into(),
            ],
        },
        SkinPreset {
            key: "win10gray".into(),
            display_name: t.t("skin.win10gray").into(),
            display_name_key: "skin.win10gray",
            author: "五笔小筑".into(),
            values: map![
                "name".into() => "win10灰／win10gray".into(),
                "author".into() => "五笔小筑 <wubixiaozhu@126.com>".into(),
                "back_color".into() => "0xfff4f4f4".into(),
                "shadow_color".into() => "0xf7606060".into(),
                "border_color".into() => "0xff305c3c".into(),
                "text_color".into() => "0xff000000".into(),
                "hilited_text_color".into() => "0xff000000".into(),
                "hilited_back_color".into() => "0x4ff4f4f4".into(),
                "hilited_shadow_color".into() => "0x00000000".into(),
                "hilited_mark_color".into() => "0xffd77800".into(),
                "hilited_label_color".into() => "0xff555555".into(),
                "hilited_candidate_text_color".into() => "0xff000000".into(),
                "hilited_comment_text_color".into() => "0xff555555".into(),
                "hilited_candidate_back_color".into() => "0x4fcccccc".into(),
                "hilited_candidate_border_color".into() => "0x00000000".into(),
                "hilited_candidate_shadow_color".into() => "0x00000000".into(),
                "label_color".into() => "0xff888888".into(),
                "candidate_text_color".into() => "0xff222222".into(),
                "comment_text_color".into() => "0xff888888".into(),
                "candidate_back_color".into() => "0x00000000".into(),
                "candidate_border_color".into() => "0x00000000".into(),
                "candidate_shadow_color".into() => "0x00000000".into(),
            ],
        },
        SkinPreset {
            key: "mint_light_blue".into(),
            display_name: t.t("skin.mint_light_blue").into(),
            display_name_key: "skin.mint_light_blue",
            author: "Mintimate".into(),
            values: map![
                "name".into() => "蓝水鸭／Mint Light Blue".into(),
                "author".into() => "Mintimate <Mintimate's Blog>".into(),
                "text_color".into() => "0x6495ed".into(),
                "back_color".into() => "0xefefef".into(),
                "label_color".into() => "0xcac9c8".into(),
                "border_color".into() => "0xefefef".into(),
                "shadow_color".into() => "0xb4000000".into(),
                "comment_text_color".into() => "0xcac9c8".into(),
                "candidate_text_color".into() => "0x424242".into(),
                "hilited_text_color".into() => "0xed9564".into(),
                "hilited_back_color".into() => "0xefefef".into(),
                "hilited_candidate_back_color".into() => "0xed9564".into(),
                "hilited_candidate_text_color".into() => "0xefefef".into(),
                "hilited_candidate_label_color".into() => "0xcac9c8".into(),
                "hilited_label_color".into() => "0xcac9c8".into(),
                "hilited_comment_text_color".into() => "0xefefef".into(),
                "nextpage_color".into() => "0x0000FF".into(),
                "prevpage_color".into() => "0x0000FF".into(),
            ],
        },
        SkinPreset {
            key: "ayaya".into(),
            display_name: t.t("skin.ayaya").into(),
            display_name_key: "skin.ayaya",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "文文／Ayaya".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "font_point".into() => 16.5.into(),
                "label_font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "label_font_point".into() => 12.into(),
                "candidate_format".into() => "[label]\u{2005}[candidate] [comment]".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 5.into(),
                "hilited_corner_radius".into() => 0.into(),
                "border_height".into() => 0.into(),
                "border_width".into() => 0.into(),
                "alpha".into() => 0.95.into(),
                "shadow_size".into() => 0.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0xFFFFFF".into(),
                "border_color".into() => "0xECE4FC".into(),
                "candidate_text_color".into() => "0x121212".into(),
                "comment_text_color".into() => "0x8E8E8E".into(),
                "label_color".into() => "0x888785".into(),
                "hilited_candidate_back_color".into() => "0xECE4FC".into(),
                "hilited_candidate_text_color".into() => "0x7A40EC".into(),
                "hilited_comment_text_color".into() => "0x8E8E8E".into(),
                "hilited_candidate_label_color".into() => "0xB18FF4".into(),
                "text_color".into() => "0x8100EB".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "ayaya_dark".into(),
            display_name: t.t("skin.ayaya_dark").into(),
            display_name_key: "skin.ayaya_dark",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "文文／Ayaya／深色".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "font_point".into() => 16.5.into(),
                "label_font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "label_font_point".into() => 12.into(),
                "candidate_format".into() => "[label]\u{2005}[candidate] [comment]".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 5.into(),
                "hilited_corner_radius".into() => 0.into(),
                "border_height".into() => 0.into(),
                "border_width".into() => 0.into(),
                "alpha".into() => 0.95.into(),
                "shadow_size".into() => 0.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0x000000".into(),
                "border_color".into() => "0xECE4FC".into(),
                "candidate_text_color".into() => "0xD2D2D2".into(),
                "comment_text_color".into() => "0x8E8E8E".into(),
                "label_color".into() => "0x888785".into(),
                "hilited_candidate_back_color".into() => "0x2C1E3C".into(),
                "hilited_candidate_text_color".into() => "0x7036E2".into(),
                "hilited_comment_text_color".into() => "0x8E8E8E".into(),
                "hilited_candidate_label_color".into() => "0x7036E2".into(),
                "text_color".into() => "0x8100EB".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "reimu".into(),
            display_name: t.t("skin.reimu").into(),
            display_name_key: "skin.reimu",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "灵梦／Reimu".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "font_point".into() => 17.into(),
                "label_font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "label_font_point".into() => 14.into(),
                "candidate_format".into() => "[label]\u{2005}[candidate] [comment]".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 7.into(),
                "hilited_corner_radius".into() => 6.into(),
                "border_height".into() => 1.into(),
                "border_width".into() => 1.into(),
                "alpha".into() => 0.95.into(),
                "shadow_size".into() => 2.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0xF5FCFD".into(),
                "candidate_text_color".into() => "0x282C32".into(),
                "comment_text_color".into() => "0x717172".into(),
                "label_color".into() => "0x888785".into(),
                "hilited_candidate_back_color".into() => "0xF5FCFD".into(),
                "hilited_candidate_text_color".into() => "0x4F00E5".into(),
                "hilited_comment_text_color".into() => "0x9F9CF2".into(),
                "hilited_candidate_label_color".into() => "0x4F00E5".into(),
                "text_color".into() => "0x6B54E9".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "reimu_dark".into(),
            display_name: t.t("skin.reimu_dark").into(),
            display_name_key: "skin.reimu_dark",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "灵梦／Reimu／深色".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "font_point".into() => 17.into(),
                "label_font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "label_font_point".into() => 14.into(),
                "candidate_format".into() => "[label]\u{2005}[candidate] [comment]".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 7.into(),
                "hilited_corner_radius".into() => 6.into(),
                "border_height".into() => 1.into(),
                "border_width".into() => 1.into(),
                "alpha".into() => 0.95.into(),
                "shadow_size".into() => 2.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0x020A00".into(),
                "border_color".into() => "0x020A00".into(),
                "candidate_text_color".into() => "0xC0C0C0".into(),
                "comment_text_color".into() => "0x717172".into(),
                "label_color".into() => "0x717172".into(),
                "hilited_candidate_back_color".into() => "0x0C140A".into(),
                "hilited_candidate_text_color".into() => "0x3100C7".into(),
                "hilited_comment_text_color".into() => "0x7772AF".into(),
                "hilited_candidate_label_color".into() => "0x3100C7".into(),
                "text_color".into() => "0x6B54E9".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "apathy".into(),
            display_name: t.t("skin.apathy").into(),
            display_name_key: "skin.apathy",
            author: "LIANG Hai".into(),
            values: map![
                "name".into() => "冷漠／Apathy".into(),
                "author".into() => "LIANG Hai".into(),
                "font_face".into() => "PingFangSC-Regular".into(),
                "font_point".into() => 16.into(),
                "label_font_face".into() => "STHeitiSC-Light".into(),
                "label_font_point".into() => 12.into(),
                "candidate_format".into() => "[label]\u{2005}[candidate] [comment]".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 5.into(),
                "alpha".into() => 0.95.into(),
                "color_space".into() => "srgb".into(),
                "back_color".into() => "0xFFFFFF".into(),
                "candidate_text_color".into() => "0xD8000000".into(),
                "comment_text_color".into() => "0x999999".into(),
                "label_color".into() => "0xE5555555".into(),
                "hilited_candidate_back_color".into() => "0xFFF0E4".into(),
                "hilited_candidate_text_color".into() => "0xEE6E00".into(),
                "hilited_comment_text_color".into() => "0x999999".into(),
                "hilited_candidate_label_color".into() => "0xF4994C".into(),
                "text_color".into() => "0x424242".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "win10".into(),
            display_name: t.t("skin.win10").into(),
            display_name_key: "skin.win10",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "WIN10".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "font_point".into() => 16.5.into(),
                "label_font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "label_font_point".into() => 12.into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 0.into(),
                "hilited_corner_radius".into() => (-6).into(),
                "border_height".into() => 7.into(),
                "border_width".into() => 6.into(),
                "spacing".into() => 10.into(),
                "color_space".into() => "srgb".into(),
                "back_color".into() => "0xFFFFFF".into(),
                "candidate_text_color".into() => "0x000000".into(),
                "comment_text_color".into() => "0x888888".into(),
                "label_color".into() => "0x888888".into(),
                "hilited_candidate_back_color".into() => "0xCC8F29".into(),
                "hilited_candidate_text_color".into() => "0xFFFFFF".into(),
                "hilited_comment_text_color".into() => "0xFFFFFF".into(),
                "hilited_candidate_label_color".into() => "0xEEDAB8".into(),
                "text_color".into() => "0x000000".into(),
                "hilited_back_color".into() => "0xFFFFFF".into(),
                "hilited_text_color".into() => "0x000000".into(),
            ],
        },
        SkinPreset {
            key: "win10_ayaya".into(),
            display_name: t.t("skin.win10_ayaya").into(),
            display_name_key: "skin.win10_ayaya",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "WIN10／文文／Ayaya".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "font_point".into() => 16.5.into(),
                "label_font_face".into() => "LXGWWenKai-Regular, PingFangSC".into(),
                "label_font_point".into() => 12.into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 0.into(),
                "hilited_corner_radius".into() => (-6).into(),
                "border_height".into() => 7.into(),
                "border_width".into() => 6.into(),
                "spacing".into() => 10.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0xFFFFFF".into(),
                "border_color".into() => "0xFFFFFF".into(),
                "candidate_text_color".into() => "0x121212".into(),
                "comment_text_color".into() => "0x8E8E8E".into(),
                "label_color".into() => "0x888785".into(),
                "hilited_candidate_back_color".into() => "0xECE4FC".into(),
                "hilited_candidate_text_color".into() => "0x7A40EC".into(),
                "hilited_comment_text_color".into() => "0x8E8E8E".into(),
                "hilited_candidate_label_color".into() => "0xB18FF4".into(),
                "text_color".into() => "0x8100EB".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "macos12_light".into(),
            display_name: t.t("skin.macos12_light").into(),
            display_name_key: "skin.macos12_light",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "高仿亮色 macOS".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "PingFangSC-Regular".into(),
                "font_point".into() => 15.into(),
                "label_font_face".into() => "PingFangSC-Regular".into(),
                "label_font_point".into() => 12.into(),
                "comment_font_face".into() => "PingFangSC-Regular".into(),
                "comment_font_point".into() => 13.into(),
                "candidate_format".into() => "[label]\u{2004}[candidate] [comment]".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 7.into(),
                "hilited_corner_radius".into() => 6.into(),
                "border_width".into() => 2.into(),
                "line_spacing".into() => 1.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0xFFFFFF".into(),
                "border_color".into() => "0xFFFFFF".into(),
                "candidate_text_color".into() => "0xD8000000".into(),
                "comment_text_color".into() => "0x3F000000".into(),
                "label_color".into() => "0x7F7F7F".into(),
                "hilited_candidate_back_color".into() => "0xD05925".into(),
                "hilited_candidate_text_color".into() => "0xFFFFFF".into(),
                "hilited_comment_text_color".into() => "0x808080".into(),
                "hilited_candidate_label_color".into() => "0xFFFFFF".into(),
                "text_color".into() => "0x3F000000".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "macos12_dark".into(),
            display_name: t.t("skin.macos12_dark").into(),
            display_name_key: "skin.macos12_dark",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "高仿暗色 macOS".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "PingFangSC-Regular".into(),
                "font_point".into() => 15.into(),
                "label_font_face".into() => "PingFangSC-Regular".into(),
                "label_font_point".into() => 12.into(),
                "comment_font_face".into() => "PingFangSC-Regular".into(),
                "comment_font_point".into() => 13.into(),
                "candidate_format".into() => "[label]\u{2004}[candidate] [comment]".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 7.into(),
                "hilited_corner_radius".into() => 6.into(),
                "border_width".into() => 2.into(),
                "line_spacing".into() => 1.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0x1E1F24".into(),
                "border_color".into() => "0x1E1F24".into(),
                "candidate_text_color".into() => "0xE8E8E8".into(),
                "comment_text_color".into() => "0x3F000000".into(),
                "label_color".into() => "0x7C7C7C".into(),
                "hilited_candidate_back_color".into() => "0xDA6203".into(),
                "hilited_candidate_text_color".into() => "0xFFFFFF".into(),
                "hilited_comment_text_color".into() => "0x808080".into(),
                "hilited_candidate_label_color".into() => "0xFFE7D6".into(),
                "text_color".into() => "0x3F000000".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "wechat_dark".into(),
            display_name: t.t("skin.wechat_dark").into(),
            display_name_key: "skin.wechat_dark",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "高仿暗色微信输入法".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "PingFangSC-Regular".into(),
                "font_point".into() => 15.into(),
                "label_font_face".into() => "PingFangSC-Regular".into(),
                "label_font_point".into() => 12.into(),
                "comment_font_face".into() => "PingFangSC-Regular".into(),
                "comment_font_point".into() => 12.into(),
                "candidate_format".into() => "[label]\u{2005}[candidate] [comment]".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 7.into(),
                "hilited_corner_radius".into() => 7.into(),
                "border_height".into() => (-2).into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0x151515".into(),
                "border_color".into() => "0x151515".into(),
                "candidate_text_color".into() => "0xB9B9B9".into(),
                "comment_text_color".into() => "0x8E8E8E".into(),
                "label_color".into() => "0x888785".into(),
                "hilited_candidate_back_color".into() => "0x74A54B".into(),
                "hilited_candidate_text_color".into() => "0xFFFFFF".into(),
                "hilited_comment_text_color".into() => "0xF0F0F0".into(),
                "hilited_candidate_label_color".into() => "0xFFFFFF".into(),
                "text_color".into() => "0xFFFFFF".into(),
                "hilited_text_color".into() => "0x777777".into(),
            ],
        },
        SkinPreset {
            key: "macos14".into(),
            display_name: t.t("skin.macos14").into(),
            display_name_key: "skin.macos14",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "高仿 macOS 14".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "PingFangSC-Regular".into(),
                "font_point".into() => 16.into(),
                "label_font_face".into() => "PingFangSC-Regular".into(),
                "label_font_point".into() => 8.into(),
                "comment_font_face".into() => "PingFangSC-Regular".into(),
                "comment_font_point".into() => 13.into(),
                "candidate_format".into() => "[label]\u{2003}\u{2003}\u{2003}[candidate] [comment]\u{2004}\u{2001}".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 7.into(),
                "hilited_corner_radius".into() => (-1).into(),
                "border_height".into() => (-4).into(),
                "border_width".into() => 2.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0xE7E8EA".into(),
                "border_color".into() => "0xE7E8EA".into(),
                "candidate_text_color".into() => "0x464647".into(),
                "comment_text_color".into() => "0x3F000000".into(),
                "label_color".into() => "0x7F7F7F".into(),
                "hilited_candidate_back_color".into() => "0xD05925".into(),
                "hilited_candidate_text_color".into() => "0xFFFFFF".into(),
                "hilited_comment_text_color".into() => "0xDCDCDC".into(),
                "hilited_candidate_label_color".into() => "0xFFFFFF".into(),
                "text_color".into() => "0x3F000000".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
        SkinPreset {
            key: "macos14_dark".into(),
            display_name: t.t("skin.macos14_dark").into(),
            display_name_key: "skin.macos14_dark",
            author: "Lufs X".into(),
            values: map![
                "name".into() => "高仿暗色 macOS 14".into(),
                "author".into() => "Lufs X <i@isteed.cc>".into(),
                "font_face".into() => "PingFangSC-Regular".into(),
                "font_point".into() => 16.into(),
                "label_font_face".into() => "PingFangSC-Regular".into(),
                "label_font_point".into() => 8.into(),
                "comment_font_face".into() => "PingFangSC-Regular".into(),
                "comment_font_point".into() => 13.into(),
                "candidate_format".into() => "[label]\u{2003}\u{2003}\u{2003}[candidate] [comment]\u{2004}\u{2001}".into(),
                "candidate_list_layout".into() => "linear".into(),
                "text_orientation".into() => "horizontal".into(),
                "inline_preedit".into() => true.into(),
                "corner_radius".into() => 7.into(),
                "hilited_corner_radius".into() => (-1).into(),
                "border_height".into() => (-4).into(),
                "border_width".into() => 2.into(),
                "color_space".into() => "display_p3".into(),
                "back_color".into() => "0x555557".into(),
                "border_color".into() => "0x0C0C0C".into(),
                "candidate_text_color".into() => "0xEEEEEE".into(),
                "comment_text_color".into() => "0x80FFFFFF".into(),
                "label_color".into() => "0x7C7C7C".into(),
                "hilited_candidate_back_color".into() => "0xCA5824".into(),
                "hilited_candidate_text_color".into() => "0xFFFFFF".into(),
                "hilited_comment_text_color".into() => "0xF0F0F0".into(),
                "hilited_candidate_label_color".into() => "0xFFFFFF".into(),
                "text_color".into() => "0x3F000000".into(),
                "hilited_text_color".into() => "0xD8000000".into(),
            ],
        },
    ]
}

pub fn list_available_skins(lang: Lang) -> Vec<(String, String)> {
    builtin_skins(lang)
        .into_iter()
        .map(|s| (s.key, s.display_name))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_skin_catalog_matches_reference_count() {
        assert_eq!(builtin_skins(Lang::Zh).len(), 21);
        assert_eq!(builtin_skins(Lang::En).len(), 21);
    }
}
